// Config for the 6 interactive objects in the scene.
// Positions are in % of the scene container (top/left), so layout stays responsive.
// `size` is the design width in % of the container; height auto-derives from the SVG aspect ratio.
const SCENE_OBJECTS = [
  {
    id: "tree",
    label: "ต้นไม้",
    sub: "Potted sprout",
    bubble: "สดชื่นชะมัด!",
    panel: "ต้นไม้กระถางตัวจิ๋ว ชอบแดดอ่อนๆ ตอนเช้า",
    cta: "รดน้ำ",
    art: "tree",
    x: 4, y: 48, w: 20,
    bubbleOffsetY: -14,
    anim: "anim-sway",
  },
  {
    id: "ball",
    label: "ลูกบอล",
    sub: "Baseball",
    bubble: "มาเล่นกันมั้ย?",
    panel: "ลูกเบสบอลเก่าๆ รอใครสักคนมาขว้างเล่น",
    cta: "โยนเล่น",
    art: "ball",
    x: 30, y: 58, w: 10,
    bubbleOffsetY: -6,
    anim: "anim-bob",
  },
  {
    id: "balloon",
    label: "ลูกโป่ง",
    sub: "Yellow balloon",
    bubble: "ลอยฟ่อง~",
    panel: "ลูกโป่งสีเหลืองสด ผูกไว้ข้างระเบียงร้าน",
    cta: "ดึงเชือก",
    art: "balloon",
    x: 60, y: 44, w: 14,
    bubbleOffsetY: -8,
    anim: "anim-float",
  },
  {
    id: "mat",
    label: "พรมปิกนิก",
    sub: "Picnic mat",
    bubble: "นั่งพักก่อนนะ",
    panel: "พรมลายทางขาว-ฟ้า เหมาะกับวันแดดอ่อน",
    cta: "ปูพรม",
    art: "mat",
    x: -4, y: 80, w: 44,
    bubbleOffsetY: -6,
    anim: "anim-pulse",
  },
  {
    id: "cushion",
    label: "เบาะ",
    sub: "Floor cushion",
    bubble: "นุ่มสุดๆ!",
    panel: "เบาะสีส้มอุ่นๆ ที่แมวข้างบ้านชอบมาแอบนอน",
    cta: "นั่งเล่น",
    art: "cushion",
    x: 44, y: 67, w: 18,
    bubbleOffsetY: -6,
    anim: "anim-pulse",
  },
  {
    id: "bowl",
    label: "ชามอาหาร",
    sub: "Food bowl",
    bubble: "หิวแล้ว!",
    panel: "ชามอาหารสีเหลือง พร้อมเสิร์ฟมื้อโปรด",
    cta: "เติมอาหาร",
    art: "bowl",
    x: 14, y: 68, w: 24,
    bubbleOffsetY: -8,
    anim: "anim-bob",
  },
];

window.SCENE_OBJECTS = SCENE_OBJECTS;
